import pandas as pd

def load_and_rename_data(path="./data/Fifa_world_cup_matches.csv"):
    df = pd.read_csv(path)

    correcoes = {
        'team1':'team',
        'team2':'opponent',
        'possession team1':'possession',
        'possession team2':'opponent_possession',
        'possession in contest':'possession_contest',
        'number of goals team1':'goals_for',
        'number of goals team2':'goals_against',
        'date':'date',
        'category':'category',
        'total attempts team1':'total_attempts',
        'total attempts team2':'opponent_total_attempts',
        'assists team1': 'assists',
        'assists team2': 'opponent_assists',
        'on target attempts team1': 'attempts_on_target',
        'on target attempts team2': 'opponent_attempts_on_target',
        'off target attempts team1': 'attempts_off_target',
        'off target attempts team2': 'opponent_attempts_off_target',
        'left channel team1': 'left_channel',
        'left channel team2': 'opponent_left_channel',
        'left inside channel team1': 'left_inside_channel',
        'left inside channel team2': 'opponent_left_inside_channel',
        'central channel team1': 'central_channel',
        'central channel team2': 'opponent_central_channel',
        'right inside channel team1': 'right_inside_channel',
        'right inside channel team2': 'opponent_right_inside_channel',
        'right channel team1': 'right_channel',
        'right channel team2': 'opponent_right_channel',
        'yellow cards team1': 'yellow_cards',
        'yellow cards team2': 'opponent_yellow_cards',
        'red cards team1': 'red_cards',
        'red cards team2': 'opponent_red_cards',
        'fouls against team1': 'fouls_committed',
        'fouls against team2': 'opponent_fouls_committed',
        'offsides team1': 'offsides',
        'offsides team2': 'opponent_offsides',
        'passes team1': 'total_passes',
        'passes team2': 'opponent_total_passes',
        'passes completed team1': 'completed_passes',
        'passes completed team2': 'opponent_completed_passes',
        'crosses completed team1': 'crosses',
        'crosses completed team2': 'opponent_crosses',
        'corners team1': 'corners',
        'corners team2': 'opponent_corners',
        'own goals team1': 'own_goals',
        'own goals team2': 'opponent_own_goals'
    }

    df = df.rename(columns=correcoes)

    df = df[[
        'team',
        'opponent',
        'possession',
        'opponent_possession',
        'possession_contest',
        'goals_for',
        'goals_against',
        'date',
        'category',
        'total_attempts',
        'opponent_total_attempts',
        'attempts_on_target',
        'opponent_attempts_on_target',
        'attempts_off_target',
        'opponent_attempts_off_target',
        'assists',
        'opponent_assists',
        'left_channel',
        'opponent_left_channel',
        'left_inside_channel',
        'opponent_left_inside_channel',
        'central_channel',
        'opponent_central_channel',
        'right_inside_channel',
        'opponent_right_inside_channel',
        'right_channel',
        'opponent_right_channel',
        'yellow_cards',
        'opponent_yellow_cards',
        'red_cards',
        'opponent_red_cards',
        'fouls_committed',
        'opponent_fouls_committed',
        'offsides',
        'opponent_offsides',
        'total_passes',
        'opponent_total_passes',
        'completed_passes',
        'opponent_completed_passes',
        'crosses',
        'opponent_crosses',
        'corners',
        'opponent_corners',
        'own_goals',
        'opponent_own_goals'
    ]]

    return df
